### ISSUE TITLE
Ingest Ridership Data

### ISSUE THREAD

**Issue by code-farmhouse** [hackoregon/transportation-systems#13]
- [ ] Convert CSV into Postgres

**Comment by znmeb** [comment]
I've got the SQL done for this - just need to build a container to run it in.

**Comment by znmeb** [comment]
The code is basically complete and running. (<https://github.com/hackoregon/ingest-ridership-data>). The plan is to integrate it with Django Rest Framework as soon as the crash data integration is complete. This one will be simpler than the crash data one; there's only one table and all the rows are geotagged.

**Comment by znmeb** [comment]
Closing - database dump is available in our Google Driver in the "Compressed Dumps" folder, file "passenger_census.backup".
