### ISSUE TITLE
Ridership data exploratory data analysis

### ISSUE THREAD

**Issue by znmeb** [hackoregon/transportation-systems#27]
I've started on this using QGIS. The first thing I'm planning on doing is an animated map of the data over time. QGIS has a plugin that makes this possible; we'd need to filter by bus line or the maps are unreadable but it looks like it can be done without any data other than what we have.

Help wanted sign is up - soliciting more ideas!!

**Comment by ben-chaney** [comment]
Eager to help out on this.

**Comment by ben-chaney** [comment]
Whoops that's clearly the "close" button did not do what I thought it did.
