### ISSUE TITLE
Rename Database Dumps to confirm to standards

### ISSUE THREAD

**Issue by bhgrant8** [hackoregon/transportation-systems#29]
Hey folks, as discussed at meeting on Tuesday, DevOps are looking to get some dbs up in development server. At this time naming conventions appears to be only blocking issue.

Tasks I see: 
1. rename our databases to append the "transportation-systems" title to beginning of all Databases. See https://github.com/hackoregon/civic-devops/issues/1#issuecomment-362922962 for source of truth
2. (Maybe optional) Standardize usage of hyphens vs underscores?
3. Update our local db variables in the django project and test if any migrations/changes are needed.
4. Provide db on google drive
5. I will upload to s3 for devops to deploy
6. Test local api connection to the dev database

I am marking this as a high priority, provided we can get this up successfully, should allow devops to move forward with some architecture work. @znmeb going to assign this to you.

**Comment by znmeb** [comment]
OK - so the new database names are `transportation-systems-odot-crash-data` and `transportation-systems-passenger-census`. The backup files will be the same names followed by `.sql.gz`.

**Comment by bhgrant8** [comment]
we have databases in s3 with proper names. closing
