### ISSUE TITLE
Update Project Documentation

### ISSUE THREAD

**Issue by code-farmhouse** [hackoregon/transportation-systems#9]

**Comment by code-farmhouse** [comment]
- [ ] Project Details
- [ ] Timeline

**Comment by znmeb** [comment]
@code-farmhouse How does one volunteer to "take" one of those documentation items? I think I should do the PostgreSQL one unless someone else is itching to do it, and I also want to do some documentation on the data ingestion processes and the geocoder.

**Comment by jbeyer16** [comment]
@code-farmhouse @znmeb seems you've "taken" them right there. I don't see why they can't be yours!

**Comment by znmeb** [comment]
The PostgreSQL/ PostGIS / pgRouting documentation (as lecture notes) is started - see https://github.com/hackoregon/data-science-pet-containers/blob/master/docs/getting-started-with-postgresql.pdf and https://github.com/hackoregon/data-science-pet-containers/tree/master/examples.

Everything's in Markdown - I'd have to tweak the heading levels and add some more screenshots but that's about all it would take for import to Read the Docs
